USE TestData;
 
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED; 

BEGIN TRANSACTION; 

SELECT ID, TestValue FROM dbo.TestItems WHERE ID=1;

UPDATE dbo.TestItems SET TestValue=100 WHERE ID=1;

WAITFOR DELAY '00:00:05';

COMMIT TRANSACTION;

SELECT ID, TestValue FROM dbo.TestItems WHERE ID=1;
