USE TestData;
 
SET TRANSACTION ISOLATION LEVEL READ COMMITTED; 

BEGIN TRANSACTION; 

SELECT ID, TestValue FROM TestItems WHERE Id=1;

WAITFOR DELAY '00:00:05';

SELECT ID, TestValue  FROM TestItems WHERE Id=1;

COMMIT TRANSACTION;


