USE TestData;  

--ALTER DATABASE TestData SET ALLOW_SNAPSHOT_ISOLATION ON  

SET TRANSACTION ISOLATION LEVEL SERIALIZABLE; 

BEGIN TRANSACTION; 

SELECT ID, TestValue FROM TestItems WHERE Id=1;

UPDATE dbo.TestItems SET TestValue=400 WHERE Id=1;

WAITFOR DELAY '00:00:05';

COMMIT TRANSACTION;

SELECT ID, TestValue  FROM TestItems WHERE Id=1;
