USE TestData;
 
SET TRANSACTION ISOLATION LEVEL SERIALIZABLE; 

BEGIN TRANSACTION; 

UPDATE dbo.TestItems SET TestValue=450 WHERE Id=1;

COMMIT TRANSACTION;

SELECT ID, TestValue  FROM TestItems WHERE Id=1;