USE TestData;
 
-- ALTER DATABASE TestData SET READ_COMMITTED_SNAPSHOT OFF;
-- ALTER DATABASE TestData SET READ_COMMITTED_SNAPSHOT ON;

SET TRANSACTION ISOLATION LEVEL READ COMMITTED; 

BEGIN TRANSACTION; 

UPDATE dbo.TestItems SET TestValue=500 WHERE Id=1;

WAITFOR DELAY '00:00:05';

COMMIT TRANSACTION;

