-- ALTER DATABASE ConcurrencyTestingEFCoreDb  SET ALLOW_SNAPSHOT_ISOLATION ON  
-- ALTER DATABASE ConcurrencyTestingEFCoreDb SET ALLOW_SNAPSHOT_ISOLATION OFF  

-- ALTER DATABASE ConcurrencyTestingEFCoreDb SET READ_COMMITTED_SNAPSHOT ON;
-- ALTER DATABASE ConcurrencyTestingEFCoreDb SET READ_COMMITTED_SNAPSHOT OFF;
 
